name: reviewdog ESLint
on:
  pull_request:
    branches:
      - develop
jobs:
  eslint:
    name: reviewdog ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - name: ESLint
        uses: reviewdog/action-eslint@v1.2.0
        with:
          github_token: ${{ secrets.TOKEN }}
      - name: Run eslint
        run: yarn lint
